name: .NET CD Workflow

on:
  workflow_call:
    inputs:
        environment:
            description: 'Environment'
            required: true
            default: 'dev'
            type: string

jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        pages: write
        id-token: write
      environment:
        name: ${{ inputs.environment }}
        url: "https://techexcel-${{ inputs.environment }}.azurewebsites.net/"
      steps:
        - uses: azure/login@v2.1.1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            # We also need to ensure that enable-AzPSSession is true. This is important for
            # using OIDC in Azure. If we were to pass in a client secret instead, we would not need
            # this setting enabled
            enable-AzPSSession: true
    
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'ghwxvgb4jngfa-${{ inputs.environment }}'
            images: ${{ secrets.ACR_LOGIN_SERVER }}/techexcel/dotnetcoreapp:${{ github.run_number }}
            
    

        
